FROM golang:1.22.5 as base 

WORKDIR /app/  

COPY go.mod .

RUN go mod download

COPY . .

RUN go build -o main .

# Final stage - Distroless/base
FROM gcr.io/distroless/ase

COPY --from=base /app/main .

COPY --from=base /app/static ./static

EXPOSE 8080

CMD [ "./main"]