pipeline{
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_TOKEN')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_PASS')
        AWS_DEFAULT_REGION = "us-east-1" 
    }
    stages {
        stage ('Git checkout'){
            steps {
                script {
                    checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/gspvsr/EKS_TERRAFORM.git']])
                }
            }
        }
        stage ('terraform init'){
            steps {
                dir('EKS') {
                    script {
                        sh 'terraform init'
                    }
                }
            }
        }
        
        stage ('terraform validate'){
            steps {
                dir('EKS') {
                    sh 'terraform validate'
                }
            }
        }

        stage ('terraform apply'){
            steps {
                dir('EKS') {
                    sh 'terraform apply --auto-approve'
                }
            }
        }
        
    }
}